# _config.yml
# variables here are of the form <variable>:string
# they can be addressed as {{ site.variable }}
# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: Meyeview

# Short description (goes below the title; it will also be used in the RSS feed)
description: Haven for the creatively impaired!

# Your name, as you want it to appear underneath each post and in the footer
author: Dan McGinn-Combs

# The directory for category index pages. Change it to something else if
# for example you want links like /categories/category1 instead of /category1
category_dir: /

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://dgcombs.github.com/

# Continue compiling even if there are errors. Keep it true, unless troubleshooting.
auto: true

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty